### ISSUE TITLE
Forum 

### ISSUE THREAD

**Issue by Daniel7729** [GimpArm/smartfriends-bridge#2]
Hi,
I didn't know that I could also write here. That's exactly what I was looking for. I just didn't want to post the data in the forum. 
Since I'm also reading stuttgart here. Doesn't that mean we could have it easier, in German? I live near Goettingen :)
gruß und Danke!
Daniel

[SFB RAW.txt](https://github.com/GimpArm/smartfriends-bridge/files/8154314/SFB.RAW.txt)

**Comment by GimpArm** [comment]
It's actually not easier for me to write in German. I do live near Stuttgart and have been for over 10 years but German is not my native language. I speak it all day at work but when I do something in my spare time I need to rest my brain. Although reading is much easier for me than writing and I tend to use more Denglish.

For your problem there was a bug in my value conversions. Basically it says it's a 32 bit value but they put a 64 bit value in there. That cause things to crash which is why not all your values were being displayed. I pushed out a new version 3.5 with this fixed so if you upgrade you should be seeing values in "currentValue" and "state" for everything. When I run your file through I can see that.

Holy crap do you have a lot of devices. The most I've ever seen, no wonder you managed to find a bug no one else has!

For your door sensors, I don't think you need to do anything but tell it that its a binary_sensor. The state is 0 and 1 which HA will understand. Class is optional but makes it a little easier in HA https://www.home-assistant.io/integrations/binary_sensor/#device-class
```
{
    "Id": 13753,
    "Type": "binary_sensor",
    "Class": "door"
}
```

For the lights it's still a little more complicated, might need to be a trial and error but here's what I thinks:
```
{
  "Id": 618,
  "Type": "light",
  "Parameters": {
    "command_topic": "{baseTopic}/{deviceId}/switchActuator/set",
    "brightness": true,
    "brightness_state_topic": "{baseTopic}/{deviceId}/brightness",
    "brightness_command_topic": "{baseTopic}/{deviceId}/brightness/set",
    "brightness_scale": 100,
    "color_mode": true,
    "color_temp_state_topic": "{baseTopic}/{deviceId}/colortemp",
    "color_temp_command_topic": "{baseTopic}/{deviceId}/colortemp/set",
    "supported_color_modes": [ "onoff", "brightness", "color_temp"]
  }
}
```

Your lights without color temp you can do the same, just remove the color temp.

```
{
  "Id": 12300,
  "Type": "light",
  "Parameters": {
    "command_topic": "{baseTopic}/{deviceId}/switchActuator/set",
    "brightness": true,
    "brightness_state_topic": "{baseTopic}/{deviceId}/brightness",
    "brightness_command_topic": "{baseTopic}/{deviceId}/brightness/set",
    "brightness_scale": 100
  }
}
```

You also have a couple lights I see that support RGB values, the ones with the "hsv" sub device. It looks to me light HA doesn't support HSV directly, they do HS and then V = brightness, so the mapping will be quite a bit more complex. I can help you with that but not right now.

I see motion detectors and stuff. I'm confident it can all be made to work but its going to take some reading at https://www.home-assistant.io/docs/mqtt/discovery/ to figure out how to map them.

**Comment by Daniel7729** [comment]
Hi,
many thanks for your effort!
I'm sorry, I automatically assumed based on where you live that you speak German. Of course we could write English 😊
Yes, there have been a few devices accumulating over the last 3 years 😉 
I've been playing with HA for 6 months now, but haven't been able to bring myself to move yet. 
Unfortunately, I'm still too unsure. 
With the SFB I know how to program it. HA is all new, and even more awkward for me at the moment. Also look on Node red, but that seems even more complicated.

Zigbee and Zwave can switch to HA without any problems, I have my sticks for that. Unfortunately, does not apply with Schellenberg and their roller shutter. 
The same with ABUS Smartvest. The alarm system is an extra device that is only integrated into the SFB. This provides the window sensors, motion detectors, smoke detectors.
If I can't take everything with me to HA, would it also be an idea to use the virtual switches to solve it? I would also like to use this in HA. Shouldn't they also work like the window sensor? I Tried it once, unfortunately without success.
But now for the update:
I installed the update - stopped addon, copied the code in, deleted the devices in Mosquitto broker, restarted HA, restarted addon.
The Mosquitto broker displayed the 4 devices again after a short time. However, all are now without function.
Shutter: displayed as up, stop, down. without function
Window sensor: unchanged; status : unknown
Lamp: Only on / off, but no longer responds to it
Here my code:
Many greetings
`[
  {
    "Id": 10044,
    "Type": "cover",
    "Class": "shutter"
  },
  {
    "Id": 6177,
    "Type": "cover",
    "Class": "shutter"
  },
  {
    "Id": 13753,
    "Type": "binary_sensor",
    "Class": "door"
  },
  {
  "Id": 618,
  "Type": "light",
  "Parameters": {
    "command_topic": "{baseTopic}/{deviceId}/switchActuator/set",
    "brightness": true,
    "brightness_state_topic": "{baseTopic}/{deviceId}/brightness",
    "brightness_command_topic": "{baseTopic}/{deviceId}/brightness/set",
    "brightness_scale": 100,
    "color_mode": true,
    "color_temp_state_topic": "{baseTopic}/{deviceId}/colortemp",
    "color_temp_command_topic": "{baseTopic}/{deviceId}/colortemp/set",
    "supported_color_modes": [ "onoff", "brightness", "color_temp"]
  }
}


]
`

**Comment by GimpArm** [comment]
If you do run a 2nd Zigbee network, change the HA to a channel other than 11. The SFB runs on 11 and you can't change it or turn it off. You'll get less interference that way.

I like HA because I don't pay a monthly fee for remote access and I can integrate a lot more things. My SFB I only use it for the Rolladen and a few Zigbee devices that don't play well with the rest of the normal network. All my other Zigbee devices are with Zigbee2Mqtt. It really depends on how much work you're willing to put into it. I'm a software engineer, so its a little easier for me to just create something new to get it working in HA, like I've contributed a couple devices to Zigbee2Mqtt. If you pair an unsupported device on SFB you can't even remove it.

I don't see anything wrong with what you have. Are there any errors in the logs?

**Comment by Daniel7729** [comment]
Thank you for th tip of the zigbee network! I will take a look for it!
I figured you were a software engineer ;) I had only learned electronics for production 20 years ago. so I only know "logical circuits". won't tell you anything, called itself SIMATIC, or Klöckner Möller. but that is almost the same as programming the SFB. :)
if you don´t pay for the remote access, do you use Duck dns or something like that? 
Port forwarding in the router?
What about Alexa? Alexa mediaplayer or something?

I restarted the addon and deleted the devices.
Unfortunately without success
the log is attached.
LOG: is copied in the first two minutes.
Button: after this
I think Button is interesting because I tried to operate the devices there. maybe you can see where it is easier there.
i hope so!
[button.txt](https://github.com/GimpArm/smartfriends-bridge/files/8162663/button.txt)
[LOG.txt](https://github.com/GimpArm/smartfriends-bridge/files/8162664/LOG.txt)

**Comment by GimpArm** [comment]
Are you sure you're on the latest version 3.5? The line number of the error in the button log doesn't match the latest version. Please you check that. Try removing the light and seeing if just the 2 Rolladen and door sensor work. I suspect the light is a lot more complicated. I'm not seeing any errors, so its probably just how these things get mapped to HA.

You have so much stuff on your SFB that I think it is sending more than 1 message per-request, which I've never seen before. Your logs are quite helpful because it has a lot of functionality I don't use. Like I have no idea what all those SwitchingSequenceStatus messages are for. Maybe something connected to automations with your thermometer. I'll try to implement some of that stuff so it at least knows what kind of message it is.

I just forward the https port (443) to an Nginx proxy which manages free SSL certificates from letsencrypt.org and forwards to my various services, one of which is HA. If you're using a Fritz!box then you don't need to use duck dns or anything like that. Fritz provides you with a dynamic name if you enable MyFRITZ! Account. You get some random numbers and letters .myfritz.net. If you want a nice name you can then buy your own domain name from any discount provider and point it to that something.myfritz.net address. I've been doing that for years and it's more responsive than the free dynamic dns providers. Although Fritz boxes have support for man of the free dynamic providers built in.

There are Alexa integrations for HA and I know people use them with a lot of success. I don't trust any companies to listen to me at home. I got pretty pissed off when I had a conversation about how stupid Madonna looked in an eye patch and then got a bunch of ads every where for eye patches. So I don't trust them any more. I have played with setting up my own voice assistant but voice control for a foreigner in Germany doesn't work very well. If I have the language in German then it has problems understanding my accent. If I have it in English then it doesn't understand German place names unless you speak them as if you have no idea how to read German. One of these days I'll get back to it.

**Comment by Daniel7729** [comment]
hi,
yes it is version 3.5
[https://bilderupload.org/image/c90030279-sfb936824c019195364746230.jpg](url)
I deleted the light from the deviceMap.json. Deleted all devices and restarted the addon.
Unfortunately, the shutters still don't work.
The window sensor has never worked, so no change

I didn't have a thermometer at the SFB. Unfortunately there isn't. Only the Smartvest sends its temperature. And I have subscribed to the weather addon. 
is their also an option to export my Scenen/Automationen? That will be very cool ;) 

I had heard of Nginx before but didn't look further. I had only ever read about Duckdns in the forum. Yes, I have a Fritz. I asked for instructions with myfritz, but the only answer was: It's the same as with duckdns ;)
I'm currently trying everything with HA. My plan is to get everything up and running once, then reinstall HA, and then NebuCasa or Duckdns/Fritz will also come along. Let's see how everything works. ;)

my son even had a similar experience with whatsapp. crazy... In the past, apartments were searched for "listening devices", today we put them in our rooms voluntarily

Please don't be angry if I answer late. I've had a new job for 4 weeks. It's still a bit chaotic at the moment and a lot to learn. I am very happy and grateful that you help me!

**Comment by Daniel7729** [comment]
Hello how are you ?
Maybe you have a new idea how to fix the shutters again?
Just wanted to report back. 
Many greetings

**Comment by GimpArm** [comment]
I’m on vacation, I’ll be back tomorrow and I have some ideas that I’ll implement on the weekend.

**Comment by Daniel7729** [comment]
I am glad to hear that!
albeit a bit late, I wish you a nice holiday.
see you soon

**Comment by Daniel7729** [comment]
Hi,
how was your holiday`?
I don´t do many at last time. But now because of the updates i try it again. 
But it still not work anything.
Du you have any new ideas?

**Comment by Daniel7729** [comment]
Hi,
I did the update and took the template out of the instructions. So now my shutters go again. Super thank you. Then I'll continue to write in the forum 😊

**Comment by Daniel7729** [comment]
Hi,

i can´t write into Forum. Because they say, i´m knew, so i can only post 3 times...
Sorry, but so i will post here, what i try do put into forum, ok?

Hi,
i put a new " Virtueller Schalter" to my Box.
The RAW look like this:

```
{
    "id": 9029,
    "name": "Virtueller Schalter Test",
    "room": "Z test",
    "gatewayDevice": "SmartFriendsBox",
    "kind": "SwitchActuator",
    "manufacturer": "${Manufacturer.SmartHomePartner}",
    "state": 0,
    "devices": {
      "switchActuator": {
        "Id": 18630,
        "description": "VirtualInput",
        "commands": {
          "On": 1,
          "Off": 0
        },
        "currentValue": 0
      },
      "wallSwitch": {
        "Id": 17344,
        "description": "VirtualOutput",
        "currentValue": 0
      }
    }
  }
```

i try to put it in a switch like this, but is doesn´t work.
```
{
      "Id": 9029,
      "Type": "switch",
      "Parameters": {
          "icon": "mdi:toggle-switch",
          "state_on": 1,
          "state_off": 0,
          "payload_on": 1,
          "payload_off": 0,
          "assumed_state": true
      }
  }
```
I also tried it with just "state" or just "payload", but that doesn't change anything.
I can press the switch on the integrations, but it jumps back to off by itself after 2-3 seconds. And nothing reacts to the change.

The other problem is my Abus Smartvest window contact.
```
{
    "id": 14163,
    "name": "Fenster Heizung",
    "room": "5 Schlafzimmer",
    "gatewayDevice": "SmartFriendsBox",
    "kind": "DoorWindowContact",
    "manufacturer": "ABUS KG",
    "state": 1,
    "devices": {
      "doorWindowContact": {
        "Id": 18300,
        "description": "AbusDoorWindowNoc",
        "currentValue": 1
      },
      "failureStatus": {
        "Id": 4147,
        "description": "AbusFailureDevice",
        "currentValue": 0
      }
    }
  },

```

I'm just trying to get this to work in a very simple way.
```
{
    "Id": 14163,
    "Type": "binary_sensor",
    "Class": "door"
  },
```

which unfortunately didn't work. It is always displayed as "unknown". so I just tried it as with the switch, it is only displayed as open.
```
{
      "Id": 14163,
      "Type": "binary_sensor",
      "Class": "door",
      "Parameters": {
          "icon": "mdi:toggle-switch",
          "state_on": 1,
          "state_off": 0,
          "payload_on": 1,
          "payload_off": 0,
          "assumed_state": true
      }
  }
```
![fenster|690x401](upload://bMn0teP3ap8VKynkwTzQjClKMHE.jpeg)
![file|516x274](upload://wpGPncc3PJYgjkeqMDxvygvfcbS.jpeg)
![mqtt|690x390](upload://7ZEU8TNGiJPNDzsgXZFEQgf90eK.jpeg)

I hope you might have an idea how I can get the two to work. The virtual switch would be much more important to me ;)
Many Thanks
