### ISSUE TITLE
[No issue] Does it work with the usb

### ISSUE THREAD

**Issue by brumouta** [GimpArm/smartfriends-bridge#5]
Does this addon works with the usb? I didn't buy yet, that's why im asking instead of trying it. Would love to know if anyone tried it yet.

https://www.amazon.de/gp/aw/d/B0784NSF6S/ref=ox_sc_act_image_2?smid=A3JWKAKR8XB7XF&psc=1

**Comment by GimpArm** [comment]
No, I’ve never had one to add that functionality.

**Comment by vednolacni** [comment]
Did anybody got this working?

**Comment by MarcCain-Scott** [comment]
This is a completely different product from the SmartFriends hub. My project accesses the proprietary network protocol of the hub to send it commands and gather information about any device registered to the hub. It does it the same way their app controls the hub. Reverse engineering their app is how I figured out a lot of things.

What is linked there is a USB stick that is used to just send and receive commands to only the Rolladen. It looks like someone did figure out most of the protocol for communicating with the device. https://github.com/Hypfer/schellenberg-qivicon-usb Based on that I could probably make an application which communicates with the stick and sends/receives commands to an external system like HA or MQTT or exposes a REST api. BUT that would be a completely different project and share nothing with my SmartFriends-Bridge project. Also I do not have one of those sticks and I have no interest in spending my money on one. If you or someone wants to either send me a stick or a 29€ Amazon gift card so I can purchase one, then I will create it. I would probably do it as a direct HA integration instead of an Add-On due to less technical limitations.

**Comment by GimpArm** [comment]
This is a completely different product from the SmartFriends hub. My project accesses the proprietary network protocol of the hub to send it commands and gather information about any device registered to the hub. It does it the same way their app controls the hub. Reverse engineering their app is how I figured out a lot of things.

What is linked there is a USB stick that is used to just send and receive commands to only the Rolladen. It looks like someone did figure out most of the protocol for communicating with the device. https://github.com/Hypfer/schellenberg-qivicon-usb Based on that I could probably make an application which communicates with the stick and sends/receives commands to an external system like HA or MQTT or exposes a REST api. BUT that would be a completely different project and share nothing with my SmartFriends-Bridge project. Also I do not have one of those sticks and I have no interest in spending my money on one. If you or someone wants to either send me a stick or a 29€ Amazon gift card so I can purchase one, then I will create it. I would probably do it as a direct HA integration instead of an Add-On due to less technical limitations.

**Comment by vednolacni** [comment]
> This is a completely different product from the SmartFriends hub. My project accesses the proprietary network protocol of the hub to send it commands and gather information about any device registered to the hub. It does it the same way their app controls the hub. Reverse engineering their app is how I figured out a lot of things.
> 
> What is linked there is a USB stick that is used to just send and receive commands to only the Rolladen. It looks like someone did figure out most of the protocol for communicating with the device. https://github.com/Hypfer/schellenberg-qivicon-usb Based on that I could probably make an application which communicates with the stick and sends/receives commands to an external system like HA or MQTT or exposes a REST api. BUT that would be a completely different project and share nothing with my SmartFriends-Bridge project. Also I do not have one of those sticks and I have no interest in spending my money on one. If you or someone wants to either send me a stick or a 29€ Amazon gift card so I can purchase one, then I will create it. I would probably do it as a direct HA integration instead of an Add-On due to less technical limitations.

That would be nice! As i have 2 usb sticks at home already. Let me know your email and i will send you a gift card.

**Comment by GimpArm** [comment]
I will be on vacation soon, so I would not begin until the 2nd half of August. I will not guarantee I can accomplish this BUT I will test connectivity and that I can manipulate my blinds following what is written in the linked repo. If I cannot get it to respond in a simple test right away, then it is possible the information in the linked repo is outdated. I will then return the USB stick and send you your money back.
Also note, the repo specifically states that it is not possible to send/receive exact position of the blinds. I will not attempt this unless I see something very simple/obvious. I suspect the hub records movement times and react based on that since part of the blind setup for the hub is to time it opening/closing. I will simply relay commands and messages from the stick. Then I will create a basic HA integration for it. There are other integrations to add the timing for position. Maybe I add it if I decide it is trivial but I will not promise anything.
Of course everything I do will be open source in a git repo, although I will create a separate repo for it.

**Comment by vednolacni** [comment]
Deal! 

![slika](https://github.com/GimpArm/smartfriends-bridge/assets/123391433/7e0c4f64-b2ae-4a2d-89e3-eb973339c7ce)

**Comment by GimpArm** [comment]
Ordered, thanks!
![image](https://github.com/GimpArm/smartfriends-bridge/assets/11071591/2ec3f542-8c04-4e9d-b9ee-9e06a1b3e453)
